name: SonarCloud Analysis

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11 (if applicable, adjust for your language)
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Fetches the SonarCloud token from GitHub secrets
        run: |
          mvn clean verify sonar:sonar \
          -Dsonar.projectKey=<your_project_key> \
          -Dsonar.organization=<your_organization_key> \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
